### ISSUE TITLE
Similar repo published

### ISSUE THREAD

**Issue by xz64** [adoppler/webpack-licenses-plugin#1]
Hi there!

I am the author of [license-webpack-plugin](https://github.com/xz64/license-webpack-plugin) which I had started a little before you started this plugin.
It looks like our plugins have similar intent.

I would like to know if you would be interested in collaborating with me on license-webpack-plugin.

If you would like to discuss in private, you can contact me on my email address listed on my github profile. Please take a look at my repo and let me know. Thank you.

**Comment by adoppler** [comment]
Nice, I hadn't seen your library, I only just recently had a chance to extract this from some internal build tools.

If you're interested in maintaining this type of plugin I can deprecate mine and open some PRs.

**Comment by xz64** [comment]
I have no problem maintaining license-webpack-plugin. I'll review the PRs as they come in.

**Comment by adoppler** [comment]
👍
